In [ ]:
!pip install -q -U ydata-profiling

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.8/400.8 kB 11.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 22.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 75.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 682.5/682.5 kB 38.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 8.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 6.0 MB/s eta 0:00:00

In [ ]:
import pandas as pd
from ydata_profiling import ProfileReport

/tmp/ipykernel_1312/2829373970.py:2: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

In [ ]:
#sptfy = pd.read_csv('datasetSpotifi.csv')
grmmys = pd.read_csv('the_grammy_awards.csv')

# Generar el reporte
profile = ProfileReport(grmmys, title="Reporte de Dataset Grammys", explorative=True)

# Mostrar el reporte dentro del notebook
profile.to_notebook_iframe()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/10 [00:00<?, ?it/s]
 20%|██        | 2/10 [00:00<00:00, 16.50it/s]
 40%|████      | 4/10 [00:00<00:00, 16.45it/s]
 60%|██████    | 6/10 [00:01<00:00,  4.90it/s]
100%|██████████| 10/10 [00:01<00:00,  6.72it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
columnas= grmmys.columns
columnas

Index(['year', 'title', 'published_at', 'updated_at', 'category', 'nominee',
       'artist', 'workers', 'img', 'winner'],
      dtype='object')

In [ ]:
lst_columnas=grmmys.columns.tolist()
lst_columnas

['year',
 'title',
 'published_at',
 'updated_at',
 'category',
 'nominee',
 'artist',
 'workers',
 'img',
 'winner']

In [ ]:
grmmys.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4810 entries, 0 to 4809
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   year          4810 non-null   int64
 1   title         4810 non-null   object
 2   published_at  4810 non-null   object
 3   updated_at    4810 non-null   object
 4   category      4810 non-null   object
 5   nominee       4804 non-null   object
 6   artist        2970 non-null   object
 7   workers       2620 non-null   object
 8   img           3443 non-null   object
 9   winner        4810 non-null   bool
dtypes: bool(1), int64(1), object(8)
memory usage: 343.0+ KB

In [ ]:
grmmys.isnull().sum()

year               0
title              0
published_at       0
updated_at         0
category           0
nominee            6
artist          1840
workers         2190
img             1367
winner             0
dtype: int64

In [ ]:
len(grmmys["title"].unique().tolist())

63

In [ ]:
grmmys.duplicated().sum()

np.int64(0)

In [ ]:
grmmys

,year,title,published_at,updated_at,category,nominee,artist,workers,img,winner
0,2019,62nd Annual GRAMMY Awards (2019),2020-05-19T05:10:28-07:00,2020-05-19T05:10:28-07:00,Record Of The Year,Bad Guy,Billie Eilish,"Finneas O'Connell, producer; Rob Kinelski & Fi...",https://www.grammy.com/sites/com/files/styles/...,True
1,2019,62nd Annual GRAMMY Awards (2019),2020-05-19T05:10:28-07:00,2020-05-19T05:10:28-07:00,Record Of The Year,"Hey, Ma",Bon Iver,"BJ Burton, Brad Cook, Chris Messina & Justin V...",https://www.grammy.com/sites/com/files/styles/...,True
2,2019,62nd Annual GRAMMY Awards (2019),2020-05-19T05:10:28-07:00,2020-05-19T05:10:28-07:00,Record Of The Year,7 rings,Ariana Grande,"Charles Anderson, Tommy Brown, Michael Foster ...",https://www.grammy.com/sites/com/files/styles/...,True
3,2019,62nd Annual GRAMMY Awards (2019),2020-05-19T05:10:28-07:00,2020-05-19T05:10:28-07:00,Record Of The Year,Hard Place,H.E.R.,"Rodney “Darkchild” Jerkins, producer; Joseph H...",https://www.grammy.com/sites/com/files/styles/...,True
4,2019,62nd Annual GRAMMY Awards (2019),2020-05-19T05:10:28-07:00,2020-05-19T05:10:28-07:00,Record Of The Year,Talk,Khalid,"Disclosure & Denis Kosiak, producers; Ingmar C...",https://www.grammy.com/sites/com/files/styles/...,True
...,...,...,...,...,...,...,...,...,...,...
4805,1958,1st Annual GRAMMY Awards (1958),2017-11-28T00:03:45-08:00,2019-09-10T01:11:09-07:00,Best Classical Performance - Instrumentalist (...,Tchaikovsky: Piano Concerto No. 1 In B Flat Mi...,NaN,"Van Cliburn, artist (Symphony Of The Air Orche...",NaN,True
4806,1958,1st Annual GRAMMY Awards (1958),2017-11-28T00:03:45-08:00,2019-09-10T01:11:09-07:00,Best Classical Performance - Instrumentalist (...,Segovia Golden Jubilee,NaN,"Andres Segovia, artist",https://www.grammy.com/sites/com/files/styles/...,True
4807,1958,1st Annual GRAMMY Awards (1958),2017-11-28T00:03:45-08:00,2019-09-10T01:11:09-07:00,Best Classical Performance - Chamber Music (In...,Beethoven: Quartet 130,NaN,"Hollywood String Quartet (Alvin Dinkin, Paul S...",NaN,True
4808,1958,1st Annual GRAMMY Awards (1958),2017-11-28T00:03:45-08:00,2019-09-10T01:11:09-07:00,Best Classical Performance - Vocal Soloist (Wi...,Operatic Recital,NaN,NaN,NaN,True
4809,1958,1st Annual GRAMMY Awards (1958),2017-11-28T00:03:45-08:00,2019-09-10T01:11:09-07:00,Best Classical Performance - Operatic Or Choral,Virtuoso,NaN,"Roger Wagner, choir director",NaN,True

In [ ]:
clmns_null

['nominee', 'artist', 'workers', 'img']

In [ ]:
# Para filtrar valores nulos en pandas, usamos .isnull() en lugar de == None
grmmys.loc[grmmys["nominee"].isnull()]

,year,title,published_at,updated_at,category,nominee,artist,workers,img,winner
2261,2000,43rd Annual GRAMMY Awards (2000),2017-11-28T00:03:45-08:00,2019-09-10T01:11:09-07:00,"Remixer of the Year, Non-Classical",NaN,NaN,NaN,NaN,True
2359,1999,42nd Annual GRAMMY Awards (1999),2017-11-28T00:03:45-08:00,2019-09-10T01:09:02-07:00,"Remixer Of The Year, Non-Classical",NaN,NaN,NaN,NaN,True
2454,1998,41st Annual GRAMMY Awards (1998),2017-11-28T00:03:45-08:00,2019-09-10T01:08:19-07:00,"Remixer Of The Year, Non-classical",NaN,NaN,NaN,NaN,True
2547,1997,40th Annual GRAMMY Awards (1997),2017-11-28T00:03:45-08:00,2019-09-10T01:07:37-07:00,"Remixer Of The Year, Non-Classical",NaN,NaN,NaN,NaN,True
4525,1965,8th Annual GRAMMY Awards (1965),2017-11-28T00:03:45-08:00,2019-09-10T01:06:59-07:00,Best New Country & Western Artist,NaN,NaN,NaN,NaN,True
4573,1964,7th Annual GRAMMY Awards (1964),2017-11-28T00:03:45-08:00,2019-09-10T01:06:11-07:00,Best New Country & Western Artist Of 1964,NaN,NaN,NaN,NaN,True

In [ ]:
grmmys.loc[grmmys["artist"].isnull()]

,year,title,published_at,updated_at,category,nominee,artist,workers,img,winner
16,2019,62nd Annual GRAMMY Awards (2019),2020-05-19T05:10:28-07:00,2020-05-19T05:10:28-07:00,Song Of The Year,Bad Guy,NaN,"Billie Eilish O'Connell & Finneas O'Connell, s...",https://www.grammy.com/sites/com/files/styles/...,True
17,2019,62nd Annual GRAMMY Awards (2019),2020-05-19T05:10:28-07:00,2020-05-19T05:10:28-07:00,Song Of The Year,Always Remember Us This Way,NaN,"Natalie Hemby, Lady Gaga, Hillary Lindsey & Lo...",https://www.grammy.com/sites/com/files/styles/...,True
18,2019,62nd Annual GRAMMY Awards (2019),2020-05-19T05:10:28-07:00,2020-05-19T05:10:28-07:00,Song Of The Year,Bring My Flowers Now,NaN,"Brandi Carlile, Phil Hanseroth, Tim Hanseroth ...",https://www.grammy.com/sites/com/files/styles/...,True
19,2019,62nd Annual GRAMMY Awards (2019),2020-05-19T05:10:28-07:00,2020-05-19T05:10:28-07:00,Song Of The Year,Hard Place,NaN,"Ruby Amanfu, Sam Ashworth, D. Arcelious Harris...",https://www.grammy.com/sites/com/files/styles/...,True
20,2019,62nd Annual GRAMMY Awards (2019),2020-05-19T05:10:28-07:00,2020-05-19T05:10:28-07:00,Song Of The Year,Lover,NaN,"Taylor Swift, songwriter (Taylor Swift)",https://www.grammy.com/sites/com/files/styles/...,True
...,...,...,...,...,...,...,...,...,...,...
4805,1958,1st Annual GRAMMY Awards (1958),2017-11-28T00:03:45-08:00,2019-09-10T01:11:09-07:00,Best Classical Performance - Instrumentalist (...,Tchaikovsky: Piano Concerto No. 1 In B Flat Mi...,NaN,"Van Cliburn, artist (Symphony Of The Air Orche...",NaN,True
4806,1958,1st Annual GRAMMY Awards (1958),2017-11-28T00:03:45-08:00,2019-09-10T01:11:09-07:00,Best Classical Performance - Instrumentalist (...,Segovia Golden Jubilee,NaN,"Andres Segovia, artist",https://www.grammy.com/sites/com/files/styles/...,True
4807,1958,1st Annual GRAMMY Awards (1958),2017-11-28T00:03:45-08:00,2019-09-10T01:11:09-07:00,Best Classical Performance - Chamber Music (In...,Beethoven: Quartet 130,NaN,"Hollywood String Quartet (Alvin Dinkin, Paul S...",NaN,True
4808,1958,1st Annual GRAMMY Awards (1958),2017-11-28T00:03:45-08:00,2019-09-10T01:11:09-07:00,Best Classical Performance - Vocal Soloist (Wi...,Operatic Recital,NaN,NaN,NaN,True
4809,1958,1st Annual GRAMMY Awards (1958),2017-11-28T00:03:45-08:00,2019-09-10T01:11:09-07:00,Best Classical Performance - Operatic Or Choral,Virtuoso,NaN,"Roger Wagner, choir director",NaN,True

In [ ]:
len(grmmys["nominee"].unique().tolist())

4132

In [ ]:
pd.set_option('display.max_rows', None)

In [ ]:
display(pd.DataFrame(grmmys["nominee"].unique().tolist()))

                                                      0
0                                               Bad Guy
1                                               Hey, Ma
2                                               7 rings
3                                            Hard Place
4                                                  Talk
5                                         Old Town Road
6                                           Truth Hurts
7                                             Sunflower
8              When We All Fall Asleep, Where Do We Go?
9                                                   I,I
10                             Norman F***ing Rockwell!
11                                        thank u, next
12                                   I Used To Know Her
13                                                    7
14                              Cuz I Love You (Deluxe)
15                                  Father Of The Bride
16                          Always Remember Us This Way
17                                 Bring My Flowers Now
18                                                Lover
19                              Norman F***ing Rockwell
20                                    Someone You Loved
21                                        Billie Eilish
22                                          Black Pumas
23                                            Lil Nas X
24                                                Lizzo
25                                        Maggie Rogers
26                                              ROSALÍA
27                                  Tank And The Bangas
28                                                 Yola
29                                               Spirit
30                                You Need To Calm Down
31                                            Boyfriend
32                                               Sucker
33                                             Señorita
34                                             Look Now
35                                                   Sì
36                                Love (Deluxe Edition)
37                                A Legendary Christmas
38                                                Walls
39                              The Lion King: The Gift
40                          No.6 Collaborations Project
41                                       Got To Keep On
42                                               Linked
43                                  Piece Of Your Heart
44                                           Underwater
45                                        Midnight Hour
46                                         No Geography
47                                                  LP5
48                           Hi This Is Flume (Mixtape)
49                                               SOLACE
50                                              Weather
51                                        Mettavolution
52                                     Ancestral Recall
53                                   Star People Nation
54                  Beat Music! Beat Music! Beat Music!
55                                              Elevate
56                                            This Land
57                                         Pretty Waste
58                                      History Repeats
59                                                Woman
60                                              Too Bad
61                                              7empest
62                        Astorolus - The Great Octopus
63                                           Humanicide
64                                             Bow Down
65                                            Unleashed
66                                        Fear Inoculum
67                                  Give Yourself A Try
68                                         Harmony Hall
69                                          Social Cues
70                                                  amo
71                                           In The End
72                                               Trauma
73                                          Feral Roots
74                                             U.F.O.F.
75                                          Assume Form
76                                                Anima
77                                            Come Home
78                                           Love Again
79                                        Could've Been
80                                   Exactly How I Feel
81                                         Roll Some Mo
82                                               Jerome
83                                           Time Today
84                                          Steady Love
85                                           Real Games
86                                       Built For Love
87                                               Say So
88                                       Look At Me Now
89                                          No Guidance
90                                           Apollo XXI
91                                             Overload
92                                               Saturn
93                                Being Human In Public
94                                              Ventura
95                                                 1123
96                                              Painted
97                                             Ella Mai
98                                                 Paul
99                                  Racks In The Middle
100                                        Middle Child
101                                                Suge
102                                            Down Bad
103                                               Clout
104                                              Higher
105                                       Drip Too Hard
106                                              Panini
107                                             Ballin'
108                                          The London
109                                               A Lot
110                                            Bad Idea
111                                          Gold Roses
112                                                Igor
113                         Revenge Of The Dreamers III
114                                       Championships
115                                        I Am > I Was
116                                        The Lost Boy
117                                   Ride Me Back Home
118                                          All Your’n
119                                  Girl Goin' Nowhere
120                                       God's Country
121                                          Speechless
122                                       Brand New Man
123                    I Don't Remember Me (Before You)
124                                       The Daughters
125                                              Common
126                        It All Comes Out In The Wash
127                                          Some Of It
128                                    While I'm Livin'
129                                       Desperate Man
130                             Stronger Than The Truth
131                                   Interstate Gospel
132                                   Center Point Road
133                                               Wings
134                                        Fairy Dreams
135                                  Homage To Kindness
136                                               Verve
137                                                Deva
138                                             Sozinho
139                                           Elsewhere
140                            Tomorrow Is The Question
141                                          The Windup
142                                         Sightseeing
143                                    12 Little Spells
144                                       Thirsty Ghost
145                                   Love & Liberation
146                                      Alone Together
147                                          Screenplay
148                                     Finding Gabriel
149                          In The Key Of The Universe
150          The Secret Between The Shadow And The Soul
151                        Christian McBride's New Jawn
152                                       Come What May
153                         The Omni-American Book Club
154                                        Triple Helix
155                                   Dancer In Nowhere
156                                          Hiding Out
157                                      One Day Wonder
158                                            Antidote
159                       Sorte!: Music By John Finbury
160                          Una Noche Con Rubén Blades
161                                               Carib
162                  Sonero: The Music Of Ismael Rivera
163                                         Love Theory
164                                 Talkin' 'Bout Jesus
165                                       See The Light
166                                      Speak The Name
167                               This Is A Move (Live)
168                                      God Only Knows
169                                          Only Jesus
170                                 Haven't Seen It Yet
171            God's Not Done With You (Single Version)
172                                        Rescue Story
173                                      Long Live Love
174                                              Goshen
175                                       Tunnel Vision
176                                         Settle Here
177            Something's Happening! A Christmas Album
178                                      Burn The Ships
179                                      I Know A Ghost
180                                        The Elements
181                                           Holy Roar
182                                           Testimony
183             Deeper Roots: Where The Bluegrass Grows
184                                       Deeper Oceans
185                                   His Name Is Jesus
186                             Gonna Sing, Gonna Shout
187                                            #Eldisco
188                                                Vida
189                                               11:11
190                                            Montaner
191                                            Fantasia
192                                       El Mal Querer
193                                            X 100Pre
194                                               Oasis
195                                      Indestructible
196                                            Almadura
197                                De Ayer Para Siempre
198                                           Caminando
199                                          Percepción
200                                         Poco A Poco
201                                      20 Aniversario
202                                                Opus
203                       A Journey Through Cuban Music
204                                    Tiempo Al Tiempo
205                                             Candela
206                                             Literal
207                                       Saint Honesty
208                                     Father Mountain
209                                       I'm On My Way
210                                        Call My Name
211                                        Faraway Look
212                                        Black Myself
213                               Crossing To Jerusalem
214                I Don't Wanna Ride The Rails No More
215                                            Oklahoma
216                                       Years To Burn
217                                     Who Are You Now
218                                    Tales Of America
219                                   Walk Through Fire
220                                        Tall Fiddler
221                      Live In Prague, Czech Republic
222                               Toil, Tears & Trouble
223                                     Royal Traveller
224                         If You Can't Stand The Heat
225                              Tall, Dark, & Handsome
226                                            Kingfish
227                         Sitting On Top Of The Blues
228                              Baby, Please Come Home
229                                   Spectacular Class
230                                       Venom & Faith
231                                       Brighter Days
232                                    Somebody Save Me
233                                             Keep On
234                                       Patty Griffin
235                                  My Finest Work Yet
236                                  Rearrange My Heart
237                                    Evening Machines
238                                         Front Porch
239                                           Good Time
240                                        Kalawai’anui
241             When It's Cold - Cree Round Dance Songs
242   Recorded Live At The 2019 New Orleans Jazz & H...
243                                    Hawaiian Lullaby
244                                             Rapture
245                                             As I Am
246     The Final Battle: Sly & Robbie vs. Roots Radics
247                                   Mass Manipulation
248                                More Work To Be Done
249                                               Celia
250                                                Gece
251                                           What Heat
252                                       African Giant
253                                        Fanm D'ayiti
254              Ageless: Songs for the Child Archetype
255                                        Flying High!
256                                   I Love Rainy Days
257                                            The Love
258                                          Winterland
259                                            Becoming
260                                   Beastie Boys Book
261   I.V. Catatonia: 20 Years As A Two-Time Cancer ...
262                                     Mr. Know-It-All
263                   Sekou Andrews & The String Theory
264                                     Sticks & Stones
265                                        Quality Time
266                                           Relatable
267                                           Right Now
268                                     Son Of Patricia
269                                           Hadestown
270   Ain't Too Proud: The Life And Times Of The Tem...
271                           Moulin Rouge! The Musical
272   The Music Of Harry Potter And The Cursed Child...
273                                           Oklahoma!
274                                      A Star Is Born
275                            The Lion King: The Songs
276   Quentin Tarantino's Once Upon A Time In Hollywood
277                                           Rocketman
278                   Spider-Man: Into The Spider-Verse
279                                           Chernobyl
280                                   Avengers: Endgame
281                           Game Of Thrones: Season 8
282                                       The Lion King
283                                Mary Poppins Returns
284                I'll Never Love Again (Film Version)
285                   The Ballad Of The Lonesome Cowboy
286                                  Girl In The Movies
287                                           Suspirium
288            Star Wars: Galaxy's Edge Symphonic Suite
289                                         Begin Again
290                                 Crucible For Crisis
291                             Love, A Beautiful Force
292                                       Walkin' Funny
293                                          Moon River
294                                          Blue Skies
295                                      Hedwig's Theme
296                                           La Novena
297                                      All Night Long
298                                              Jolene
299                                   Marry Me A Little
300                                    Over The Rainbow
301                   12 Little Spells (Thoracic Spine)
302                                       Chris Cornell
303                              Anónimas & Resilientes
304                                     Hold That Tiger
305                                         Intellexual
306   Woodstock: Back To The Garden - The Definitive...
307                                 Gold In A Brass Age
308                                1963: New Directions
309                      The Radio Recordings 1939–1945
310                           Stax '68: A Memphis Story
311                     The Complete Cuban Jam Sessions
312                      The Gospel According To Malaco
313                          Pedal Steal + Four Corners
314    Pete Seeger: The Smithsonian Folkways Collection
315   The Girl From Chickasaw County - The Complete ...
316       The Great Comeback: Horowitz At Carnegie Hall
317   Kankyo Ongaku: Japanese Ambient, Environmental...
318                                    All These Things
319                                       Run Home Slow
320                                             Scenery
321                                             Finneas
322                                       Jack Antonoff
323                                        Dan Auerbach
324                                           John Hill
325                                          Ricky Reed
326      I Rise (Tracy Young's Pride Intro Radio Remix)
327                      Mother's Daughter (Wuki Remix)
328                       The One (High Contrast Remix)
329                                  Swim (ford. Remix)
330                             Work It (Soulwax Remix)
331                                                 LUX
332                                      Chain Tripping
333                         Kverndokk: Symphonic Dances
334                                The Orchestral Organ
335                                          The Savior
336                                    Riley: Sun Rings
337                        Aequa - Anna Thorvaldsdóttir
338                            Bruckner: Symphony No. 9
339                 Rachmaninoff - Hermitage Piano Trio
340                             Wolfe: Fire In My Mouth
341                                    Blanton Alspaugh
342                                      James Ginsburg
343                       Marina A. Ledin, Victor Ledin
344                                     Morten Lindberg
345                                        Dirk Sobotka
346                                     Norman: Sustain
347                       Copland: Billy The Kid; Grohg
348                                       Transatlantic
349                    Weinberg: Symphonies Nos. 2 & 21
350                           Picker: Fantastic Mr. Fox
351                Benjamin: Lessons In Love & Violence
352                                       Berg: Wozzeck
353   Charpentier: Les Arts Florissants; Les Plaisir...
354                                   Wagner: Lohengrin
355                      Duruflé: Complete Choral Works

In [ ]:
grmmys.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4810 entries, 0 to 4809
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   year          4810 non-null   int64
 1   title         4810 non-null   object
 2   published_at  4810 non-null   object
 3   updated_at    4810 non-null   object
 4   category      4810 non-null   object
 5   nominee       4804 non-null   object
 6   artist        2970 non-null   object
 7   workers       2620 non-null   object
 8   img           3443 non-null   object
 9   winner        4810 non-null   bool
dtypes: bool(1), int64(1), object(8)
memory usage: 343.0+ KB

In [ ]:
list_published= grmmys["published_at"].unique().tolist()

In [ ]:
print(list_published)

['2020-05-19T05:10:28-07:00', '2018-12-06T23:48:49-08:00', '2018-05-22T03:08:24-07:00', '2017-11-28T00:03:45-08:00']

In [ ]:
list_updated= grmmys["updated_at"].unique().tolist()

In [ ]:
list_updated

['2020-05-19T05:10:28-07:00',
 '2019-09-10T01:06:11-07:00',
 '2019-09-10T01:09:02-07:00',
 '2020-09-01T12:16:40-07:00',
 '2019-09-10T01:06:59-07:00',
 '2019-09-10T01:07:37-07:00',
 '2019-09-10T01:08:19-07:00',
 '2019-09-10T01:11:09-07:00',
 '2017-11-28T00:03:45-08:00',
 '2019-09-10T01:11:48-07:00']

In [ ]:
cat= pd.DataFrame(grmmys["category"].unique().tolist())

In [ ]:
display(cat)

                                                     0
0                                   Record Of The Year
1                                    Album Of The Year
2                                     Song Of The Year
3                                      Best New Artist
4                            Best Pop Solo Performance
5                       Best Pop Duo/Group Performance
6                     Best Traditional Pop Vocal Album
7                                 Best Pop Vocal Album
8                                 Best Dance Recording
9                          Best Dance/Electronic Album
10                Best Contemporary Instrumental Album
11                               Best Rock Performance
12                              Best Metal Performance
13                                      Best Rock Song
14                                     Best Rock Album
15                        Best Alternative Music Album
16                                Best R&B Performance
17                    Best Traditional R&B Performance
18                                       Best R&B Song
19                       Best Urban Contemporary Album
20                                      Best R&B Album
21                                Best Rap Performance
22                           Best Rap/Sung Performance
23                                       Best Rap Song
24                                      Best Rap Album
25                       Best Country Solo Performance
26                  Best Country Duo/Group Performance
27                                   Best Country Song
28                                  Best Country Album
29                                  Best New Age Album
30                           Best Improvised Jazz Solo
31                               Best Jazz Vocal Album
32                        Best Jazz Instrumental Album
33                      Best Large Jazz Ensemble Album
34                               Best Latin Jazz Album
35                        Best Gospel Performance/Song
36   Best Contemporary Christian Music Performance/...
37                                   Best Gospel Album
38             Best Contemporary Christian Music Album
39                             Best Roots Gospel Album
40                                Best Latin Pop Album
41         Best Latin Rock, Urban or Alternative Album
42   Best Regional Mexican Music Album (Including T...
43                           Best Tropical Latin Album
44                     Best American Roots Performance
45                            Best American Roots Song
46                                Best Americana Album
47                                Best Bluegrass Album
48                        Best Traditional Blues Album
49                       Best Contemporary Blues Album
50                                     Best Folk Album
51                     Best Regional Roots Music Album
52                                   Best Reggae Album
53                              Best World Music Album
54                         Best Children's Music Album
55   Best Spoken Word Album (Includes Poetry, Audio...
56                                   Best Comedy Album
57                          Best Musical Theater Album
58        Best Compilation Soundtrack For Visual Media
59              Best Score Soundtrack For Visual Media
60                  Best Song Written For Visual Media
61                       Best Instrumental Composition
62        Best Arrangement, Instrumental or A Cappella
63            Best Arrangement, Instruments and Vocals
64                              Best Recording Package
65       Best Boxed Or Special Limited Edition Package
66                                    Best Album Notes
67                               Best Historical Album
68                Best Engineered Album, Non-Classical
69                 Producer Of The Year, Non-Classical
70                              Best Remixed Recording
71                          Best Immersive Audio Album
72                    Best Engineered Album, Classical
73                     Producer Of The Year, Classical
74                         Best Orchestral Performance
75                                Best Opera Recording
76                             Best Choral Performance
77       Best Chamber Music/Small Ensemble Performance
78                    Best Classical Instrumental Solo
79                     Best Classical Solo Vocal Album
80                           Best Classical Compendium
81             Best Contemporary Classical Composition
82                                    Best Music Video
83                                     Best Music Film
84                               Best Children's Album
85                           Best Surround Sound Album
86                         Best Rap/Sung Collaboration
87                                    Best Blues Album
88               Best Remixed Recording, Non-Classical
89                         Best Pop Instrumental Album
90                        Best Dance/Electronica Album
91   Best Gospel/Contemporary Christian Music Perfo...
92                                    Best Gospel Song
93              Best Contemporary Christian Music Song
94                       Best Instrumental Arrangement
95   Best Instrumental Arrangement Accompanying Voc...
96                           Best Classical Vocal Solo
97                    Best Hard Rock/Metal Performance
98            Best Contemporary Classical  Composition
99                         Best Short Form Music Video
100                         Best Long Form Music Video
101               Best Latin Pop, Rock, Or Urban Album
102              Best Regional Mexican Or Tejano Album
103                        Best Banda Or Norteño Album
104                    Best Small Ensemble Performance
105                  Best Female Pop Vocal Performance
106                    Best Male Pop Vocal Performance
107  Best Pop Performance By A Duo Or Group With Vo...
108                 Best Pop Collaboration With Vocals
109                  Best Pop Instrumental Performance
110                        Best Electronic/Dance Album
111                   Best Solo Rock Vocal Performance
112  Best Rock Performance By A Duo Or Group With V...
113                         Best Hard Rock Performance
114                 Best Rock Instrumental Performance
115                  Best Female R&B Vocal Performance
116                    Best Male R&B Vocal Performance
117  Best R&B Performance By A Duo Or Group With Vo...
118             Best Traditional R&B Vocal Performance
119                 Best Urban/Alternative Performance
120                        Best Contemporary R&B Album
121                          Best Rap Solo Performance
122             Best Rap Performance By A Duo Or Group
123              Best Female Country Vocal Performance
124                Best Male Country Vocal Performance
125  Best Country Performance By A Duo Or Group Wit...
126             Best Country Collaboration With Vocals
127              Best Country Instrumental Performance
128                       Best Contemporary Jazz Album
129  Best Jazz Instrumental Album, Individual or Group
130                            Best Gospel Performance
131                      Best Rock Or Rap Gospel Album
132                 Best Pop/Contemporary Gospel Album
133  Best Southern, Country, Or Bluegrass Gospel Album
134                      Best Traditional Gospel Album
135                 Best Contemporary R&B Gospel Album
136        Best Latin Rock, Alternative Or Urban Album
137                                  Best Tejano Album
138                                 Best Norteño Album
139                                   Best Banda Album
140                        Best Traditional Folk Album
141                       Best Contemporary Folk Album
142                          Best Hawaiian Music Album
143                   Best Native American Music Album
144                   Best Zydeco Or Cajun Music Album
145                 Best Traditional World Music Album
146                Best Contemporary World Music Album
147                    Best Musical Album For Children
148                Best Spoken Word Album For Children
149  Best Spoken Word Album (Includes Poetry, Audio...
150                            Best Musical Show Album
151  Best Compilation Soundtrack Album For Motion P...
152  Best Score Soundtrack Album For Motion Picture...
153  Best Song Written For Motion Picture, Televisi...
154                               Best Classical Album
155  Best Instrumental Soloist(s) Performance (with...
156  Best Instrumental Soloist Performance (without...
157                     Best Chamber Music Performance
158                   Best Classical Vocal Performance
159            Best Classical Contemporary Composition
160                     Best Classical Crossover Album
161                        Best Regional Mexican Album
162                        Best Jazz Instrumental Solo
163               Best Latin Rock Or Alternative Album
164                             Best Latin Urban Album
165             Best Contemporary Folk/Americana Album
166                                   Best Polka Album
167                Best Mexican/Mexican-American Album
168  Best Pop Performance By A Duo Or Group With Vocal
169  Best Rock Performance By A Duo Or Group With V...
170  Best Country Performance By A Duo Or Group Wit...
171                             Best Rock Gospel Album
172  Best Southern, Country, or Bluegrass Gospel Album
173                 Best Traditional Soul Gospel Album
174                Best Contemporary Soul Gospel Album
175                  Best Gospel Choir Or Chorus Album
176                  Best Latin Rock/Alternative Album
177              Best Traditional Tropical Latin Album
178                          Best Salsa/Merengue Album
179                             Best Spoken Word Album
180  Best Small Ensemble Performance (with or witho...
181  Best Compilation Soundtrack Album For A Motion...
182  Best Score Soundtrack Album For A Motion Pictu...
183  Best Song Written For A Motion Picture, Televi...
184                 Best Female Rock Vocal Performance
185                   Best Male Rock Vocal Performance
186                   Best Female Rap Solo Performance
187                     Best Male Rap Solo Performance
188  Best R&B Performance By A Duo Or Group With Vocal
189                                   Best Salsa Album
190                                Best Merengue Album
191                           Best Spoken Comedy Album
192                   Best Traditional R&B Vocal Album
193                Best Spoken Word Album for Children
194                       Best Boxed Recording Package
195  Best Song Written For A Motion Picture, Televi...
196  Best Instrumental Arrangement Accompanying A V...
197                 Remixer of the Year, Non-Classical
198                                     Best Pop Album
199             Best Traditional Pop Vocal Performance
200                 Best Alternative Music Performance
201                           Best Rhythm & Blues Song
202                 Best Contemporary Jazz Performance
203                        Best Jazz Vocal Performance
204  Best Jazz Instrumental Performance, Individual...
205               Best Large Jazz Ensemble Performance
206                        Best Latin Jazz Performance
207                         Best Latin Pop Performance
208            Best Latin Rock/Alternative Performance
209        Best Traditional Tropical Latin Performance
210                             Best Salsa Performance
211                          Best Merengue Performance
212                  Best Mexican-American Performance
213                            Best Tejano Performance
214                              Best Soundtrack Album
215  Best Instrumental Composition Written For A Mo...
216              Best Engineered Album - Non-Classical
217                 Remixer Of The Year, Non-Classical
218  Best Instrumental Soloist(s) Performance (With...
219  Best Instrumental Soloist Performance (Without...
220  Best Small Ensemble Performance (With Or Witho...
221                    Best Tropical Latin Performance
222            Best Mexican-American Music Performance
223                      Best Tejano Music Performance
224  Best Instrumental Composition Written For A Mo...
225  Best Song Written For A Motion Picture Or For ...
226  Best Instrumental Arrangement Accompanying Voc...
227                 Remixer Of The Year, Non-classical
228   Best Southern, Country Or Bluegrass Gospel Album
229     Best Mexican-American/Tejano Music Performance
230  Best Song Written Specifically For A Motion Pi...
231   Best Country Vocal Performance By A Duo Or Group
232  Best Southern Gospel, Country Gospel Or Bluegr...
233             Best Gospel Album By A Choir Or Chorus
234              Best Spoken Word Or Non-Musical Album
235  Best Instrumental Arrangement With Accompanyin...
236                     Best Recording Package - Boxed
237                               Producer Of The Year
238                Best Classical Engineered Recording
239                     Classical Producer Of The Year
240                       Best Music Video, Short Form
241                        Best Music Video, Long Form
242                       Best Pop Vocal Collaboration
243                   Best Country Vocal Collaboration
244  Best Instrumental Arrangement With Accompanyin...
245  Best Instrumental Soloist Performance (With Or...
246  Best Instrumental Soloist Performance Without ...
247                 Best Pop Vocal Performance, Female
248                   Best Pop Vocal Performance, Male
249                  Best Rock Vocal Performance, Solo
250              Best Hard Rock Performance With Vocal
251                  Best Metal Performance With Vocal
252                 Best R&B Vocal Performance, Female
253                   Best R&B Vocal Performance, Male
254  Best Contemporary Jazz Performance (Instrumental)
255             Best Country Vocal Performance, Female
256               Best Country Vocal Performance, Male
257                        Best Mexican-American Album
258                      Best Music Video - Short Form
259                         Best Music Video-Long Form
260                Best Arrangement On An Instrumental
261                  Best Performance Of A Choral Work
262  Best Classical Performance-Instrumental Solois...
263  Best Classical Performance-Instrumental Solois...
264                      Best Contemporary Composition
265               Best Engineered Recording, Classical
266                Best Rock Vocal Performance, Female
267                  Best Rock Vocal Performance, Male
268                  Best R&B Instrumental Performance
269                Best Rock/Contemporary Gospel Album
270                              Best Pop Gospel Album
271                         Best Southern Gospel Album
272                            Best Album For Children
273                       Best Music Video - Long Form
274               Producer Of The Year (Non-Classical)
275                                 Best Album Package
276  Best Classical Performance - Instrumental Solo...
277  Best Classical Performance - Instrumental Solo...
278                   Best Traditional Pop Performance
279          Best Jazz Instrumental Performance, Group
280               Best Gospel Album By Choir Or Chorus
281               Producer Of The Year (Non Classical)
282           Best Instrumental Soloist With Orchestra
283  Best Classical Performance Instrumental Solo W...
284                       Best Classical Vocal Soloist
285                           Best New Age Performance
286                       Best Jazz Fusion Performance
287                Best Jazz Vocal Performance, Female
288                  Best Jazz Vocal Performance, Male
289        Best Jazz Instrumental Performance, Soloist
290       Best Jazz Instrumental Performance, Big Band
291                           Best Bluegrass Recording
292           Best Traditional Soul Gospel Performance
293                   Best Traditional Blues Recording
294                  Best Contemporary Blues Recording
295                    Best Traditional Folk Recording
296                   Best Contemporary Folk Recording
297                              Best Reggae Recording
298                               Best Polka Recording
299                        Best Recording For Children
300                              Best Comedy Recording
301          Best Spoken Word Or Non-Musical Recording
302                       Best Musical Cast Show Album
303          Best Engineered Recording - Non-Classical
304         Best Choral Performance (Other Than Opera)
305  Best Classical Performance, Instrumental Soloi...
306  Best Classical Performance, Instrumental Soloi...
307  Best Chamber Music Or Other Small Ensemble Per...
308              Best Engineered Recording - Classical
309          Best Jazz Vocal Performance, Duo Or Group
310  Best Jazz Instrumental Performance, Soloist (O...
311              Best Gospel Vocal Performance, Female
312                Best Gospel Vocal Performance, Male
313  Best Gospel Vocal Performance By A Duo, Group,...
314  Best Soul Gospel Vocal Performance, Male Or Fe...
315  Best Soul Gospel Vocal Performance Duo, Group,...
316  Best Album Of Original Instrumental Background...
317  Best Song Written Specifically For A Motion Pi...
318  Best Instrumental Arrangement Accompanying Vocals
319  Best Classical Performance - Instrumental Solo...
320           Best Classical Vocal Soloist Performance
321  Best Pop Instrumental Performance (Orchestra, ...
322  Best Rock Instrumental Performance (Orchestra,...
323  Best Hard Rock/Metal Performance Vocal Or Inst...
324  Best R&B Instrumental Performance (Orchestra, ...
325  Best Jazz Instrumental Performance Soloist (On...
326  Best Country Instrumental Performance (Orchest...
327   Best Bluegrass Recording (Vocal Or Instrumental)
328                    Best Gospel Performance, Female
329                      Best Gospel Performance, Male
330  Best Gospel Performance By A Duo Or Group, Cho...
331               Best Soul Gospel Performance, Female
332                 Best Soul Gospel Performance, Male
333  Best Soul Gospel Performance By A Duo, Group, ...
334                       Best Performance Music Video
335                           Best Concept Music Video
336                          Best Orchestral Recording
337  Best Classical Performance - Instrumental Solo...
338  Best Classical Performance - Instrumental Solo...
339  Best Jazz Fusion Performance, Vocal Or Instrum...
340               Best Country Vocal Performance, Duet
341  Best Album Or Original Instrumental Background...
342              Producer Of The Year, (Non Classical)
343  Best Pop Instrumental Performance, (Orchestra,...
344                             Best New Age Recording
345          Best Country Vocal Solo Performance, Male
346                Best Classical Orchestral Recording
347  Best Classical Performance - Instrumental Solo...
348                     Best Inspirational Performance
349          Best Ethnic Or Traditional Folk Recording
350  Best Album Of Original Score Written For A Mot...
351                               Best Cast Show Album
352      Best Vocal Arrangement For Two Or More Voices
353          Best Engineered Recording - Non Classical
354  Best Classical Performance - Instrumental Solo...
355  Best Classical Performance - Instrumental Solo...
356                          Best New Classical Artist
357          Best Gospel Performance By A Duo Or Group
358     Best Soul Gospel Performance By A Duo Or Group
359                             Best Video, Short Form
360                                   Best Video Album
361                     Best New Classical Composition